spring.profiles.active=dev

server.port=8080

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=10MB

label.maxUploadSizeExc=El archivo proporcionado excede el tamaNo mAximo permitido:  
label.uploadSizeExc=Error al cargar el archivo 
label.downloadSizeExc=Error al descargar el archivo

config.bucket.name=workshop
config.bucket.minio.endpoint=http://localhost:9000
config.bucket.minio.user=admin
config.bucket.minio.pass=admin123
config.bucket.minio.token=123

config.cache.link.expiry=15


config.api.documentMgmt.basePath=/document-management
config.api.documentMgmt.upload=/uploadFile
config.api.documentMgmt.search=/search
config.api.documentMgmt.download="/download/{documentId}"